# Generated by Django 5.0 on 2026-01-13 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=100, verbose_name='职位名称')),
                ('job_type', models.CharField(choices=[('全职', '全职'), ('实习', '实习'), ('兼职', '兼职')], max_length=20, verbose_name='职位类型')),
                ('city', models.CharField(max_length=50, verbose_name='工作城市')),
                ('salary_min', models.IntegerField(verbose_name='最低薪资(k)')),
                ('salary_max', models.IntegerField(verbose_name='最高薪资(k)')),
                ('education_req', models.CharField(default='不限', max_length=20, verbose_name='学历要求')),
                ('exp_req', models.CharField(default='不限', max_length=20, verbose_name='经验要求')),
                ('job_tags', models.CharField(help_text='用于匹配度计算，如: Python,后端', max_length=255, verbose_name='职位标签')),
                ('description', models.TextField(verbose_name='职位描述')),
                ('status', models.SmallIntegerField(choices=[(0, '待审'), (1, '招聘中'), (2, '已下架')], default=0, verbose_name='职位状态')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('recruiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.recruiter', verbose_name='发布企业')),
            ],
            options={
                'verbose_name': '职位信息',
                'verbose_name_plural': '职位信息',
            },
        ),
        migrations.CreateModel(
            name='JobCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collect_time', models.DateTimeField(auto_now_add=True, verbose_name='收藏时间')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.job', verbose_name='收藏职位')),
                ('seeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.jobseeker', verbose_name='求职者')),
            ],
            options={
                'verbose_name': '职位收藏',
                'verbose_name_plural': '职位收藏',
                'unique_together': {('seeker', 'job')},
            },
        ),
    ]
