# Generated by Django 5.0 on 2026-01-13 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruiter',
            name='license',
            field=models.FileField(blank=True, upload_to='licenses/%Y/%m/', verbose_name='认证文件'),
        ),
    ]
