# Generated by Django 5.0 on 2026-01-13 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume_title', models.CharField(max_length=50, verbose_name='简历标题')),
                ('resume_file', models.FileField(upload_to='resumes/%Y/%m/', verbose_name='简历附件')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('seeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.jobseeker', verbose_name='求职者')),
            ],
            options={
                'verbose_name': '简历附件',
                'verbose_name_plural': '简历附件',
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.SmallIntegerField(choices=[(0, '已投递'), (1, '被查看'), (2, '面试邀请'), (3, '录用'), (4, '不合适')], default=0, verbose_name='投递状态')),
                ('hr_feedback', models.CharField(blank=True, max_length=255, verbose_name='HR反馈')),
                ('apply_time', models.DateTimeField(auto_now_add=True, verbose_name='投递时间')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.job', verbose_name='申请职位')),
                ('seeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.jobseeker', verbose_name='求职者')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruitment.resume', verbose_name='投递简历')),
            ],
            options={
                'verbose_name': '投递记录',
                'verbose_name_plural': '投递记录',
            },
        ),
    ]
