# Generated by Django 5.0 on 2026-01-13 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecruiterActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.SmallIntegerField(choices=[(1, '查看简历'), (2, '发起面试')], verbose_name='行为类型')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='发生时间')),
                ('recruiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.recruiter', verbose_name='招聘者')),
                ('seeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.jobseeker', verbose_name='涉及求职者')),
            ],
            options={
                'verbose_name': '招聘者行为日志',
                'verbose_name_plural': '招聘者行为日志',
            },
        ),
        migrations.CreateModel(
            name='RecruiterRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_score', models.FloatField(verbose_name='匹配度')),
                ('recommend_rule', models.CharField(default='static', max_length=50, verbose_name='推荐规则')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='计算时间')),
                ('recruiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.recruiter', verbose_name='招聘者')),
                ('seeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.jobseeker', verbose_name='推荐人才')),
            ],
            options={
                'verbose_name': '人才推荐结果',
                'verbose_name_plural': '人才推荐结果',
            },
        ),
        migrations.CreateModel(
            name='SeekerActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.SmallIntegerField(choices=[(1, '浏览'), (2, '收藏'), (3, '投递')], verbose_name='行为类型')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='发生时间')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.job', verbose_name='涉及职位')),
                ('seeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.jobseeker', verbose_name='求职者')),
            ],
            options={
                'verbose_name': '求职者行为日志',
                'verbose_name_plural': '求职者行为日志',
            },
        ),
        migrations.CreateModel(
            name='SeekerRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_score', models.FloatField(verbose_name='匹配度')),
                ('recommend_rule', models.CharField(default='static', max_length=50, verbose_name='推荐规则')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='计算时间')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.job', verbose_name='推荐职位')),
                ('seeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.jobseeker', verbose_name='求职者')),
            ],
            options={
                'verbose_name': '职位推荐结果',
                'verbose_name_plural': '职位推荐结果',
            },
        ),
    ]
